<?php
/**
 * Firebase Realtime Database "connection" via REST
 * ------------------------------------------------
 * Usage examples:
 *
 * // READ a node
 * $docVic = fb_get('/doc_vic');                 // returns assoc array (or null)
 *
 * // CREATE (push) under /doc_vic (generates unique key)
 * $key = fb_post('/doc_vic', ["name"=>"Ezra","age"=>20,"course"=>"BSIT"]); // returns generated key
 *
 * // UPSERT (set) at a fixed path
 * fb_put('/doc_vic/users/u123', ["name"=>"Ezra"]);
 *
 * // UPDATE some fields (merge)
 * fb_patch('/doc_vic/users/u123', ["course"=>"BSIT"]);
 *
 * // DELETE
 * fb_delete('/doc_vic/users/u123');
 */

/* -----------------------------
   1) CONFIG
------------------------------*/

// Your database root (no trailing slash, no .json)
$FIREBASE_DB_URL = "https://belvic-9f87a-default-rtdb.firebaseio.com";

// OPTIONAL: If your rules require auth, put an ID token or DB secret here.
// Leave empty string "" if your rules are public (NOT recommended for production).
$FIREBASE_AUTH = ""; // e.g. "eyJhbGciOiJSUzI1NiIsImtpZCI6..."


/* -----------------------------
   2) INTERNAL UTILS
------------------------------*/

/**
 * Normalize a path like "/doc_vic/users" to a proper URL:
 *   https://.../doc_vic/users.json[?auth=...]
 */
function fb_build_url(string $path): string {
    global $FIREBASE_DB_URL, $FIREBASE_AUTH;

    // Ensure leading slash
    if ($path === '' || $path[0] !== '/') $path = '/' . $path;

    // Append .json
    $url = rtrim($FIREBASE_DB_URL, '/') . $path . '.json';

    // Add ?auth= token if provided
    if (!empty($FIREBASE_AUTH)) {
        $url .= (strpos($url, '?') === false ? '?' : '&') . 'auth=' . urlencode($FIREBASE_AUTH);
    }

    return $url;
}

/**
 * Core request function
 * @param string $method  GET|POST|PUT|PATCH|DELETE
 * @param string $path    e.g. "/doc_vic"
 * @param array|null $data Assoc array payload (or null)
 * @return array{ok:bool, status:int, data:mixed, error:?string}
 */
function fb_request(string $method, string $path, ?array $data = null): array {
    $url  = fb_build_url($path);
    $ch   = curl_init($url);
    $json = $data === null ? null : json_encode($data, JSON_UNESCAPED_UNICODE);

    $headers = ["Content-Type: application/json"];
    $opts = [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_CUSTOMREQUEST  => $method,
        CURLOPT_HTTPHEADER     => $headers,
        CURLOPT_TIMEOUT        => 20,
    ];
    if ($json !== null) {
        $opts[CURLOPT_POSTFIELDS] = $json;
    }

    curl_setopt_array($ch, $opts);
    $raw = curl_exec($ch);
    $err = curl_error($ch);
    $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($raw === false) {
        return ["ok" => false, "status" => 0, "data" => null, "error" => $err ?: "cURL error"];
    }

    // Firebase returns JSON; decode cautiously
    $decoded = json_decode($raw, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        // not JSON (rare), return raw string
        $decoded = $raw;
    }

    $ok = $status >= 200 && $status < 300;
    return ["ok" => $ok, "status" => $status, "data" => $decoded, "error" => $ok ? null : ($decoded['error'] ?? $raw)];
}


/* -----------------------------
   3) PUBLIC HELPERS
------------------------------*/

/**
 * Read a node (GET)
 * @return mixed (assoc array, scalar, or null)
 */
function fb_get(string $path) {
    $res = fb_request('GET', $path, null);
    if (!$res['ok']) {
        error_log("fb_get error ($path): {$res['status']} - {$res['error']}");
        return null;
    }
    return $res['data'];
}

/**
 * Create (POST) — pushes a new child with autogenerated key under $path
 * @return string|null The generated key, or null on error
 */
function fb_post(string $path, array $data): ?string {
    $res = fb_request('POST', $path, $data);
    if (!$res['ok']) {
        error_log("fb_post error ($path): {$res['status']} - {$res['error']}");
        return null;
    }
    // Firebase responds with {"name": "<generatedKey>"}
    return is_array($res['data']) && isset($res['data']['name']) ? $res['data']['name'] : null;
}

/**
 * Upsert at a fixed path (PUT) — overwrites the node at $path
 */
function fb_put(string $path, array $data): bool {
    $res = fb_request('PUT', $path, $data);
    if (!$res['ok']) {
        error_log("fb_put error ($path): {$res['status']} - {$res['error']}");
    }
    return $res['ok'];
}

/**
 * Patch (merge) some fields at $path
 */
function fb_patch(string $path, array $data): bool {
    $res = fb_request('PATCH', $path, $data);
    if (!$res['ok']) {
        error_log("fb_patch error ($path): {$res['status']} - {$res['error']}");
    }
    return $res['ok'];
}

/**
 * Delete a node
 */
function fb_delete(string $path): bool {
    $res = fb_request('DELETE', $path, null);
    if (!$res['ok']) {
        error_log("fb_delete error ($path): {$res['status']} - {$res['error']}");
    }
    return $res['ok'];
}


/* -----------------------------
   4) OPTIONAL CONVENIENCE ALIASES
------------------------------*/

/**
 * Insert example (like your previous snippet): pushes under /doc_vic
 * Usage:
 *   $key = fb_insert_doc_vic(["name"=>"Ezra","age"=>20,"course"=>"BSIT"]);
 */
function fb_insert_doc_vic(array $data): ?string {
    return fb_post('/doc_vic', $data);
}

/**
 * List all /doc_vic entries as a clean array (works if node is a map or array)
 */
function fb_list_doc_vic(): array {
    $node = fb_get('/doc_vic');
    if (!$node) return [];
    if (is_array($node)) {
        // If array had null holes, filter them out
        if (array_keys($node) === range(0, count($node) - 1)) {
            return array_values(array_filter($node, fn($v) => is_array($v)));
        }
        // If object map: return values
        return array_values(array_filter($node, fn($v) => is_array($v)));
    }
    return [];
}
